id: P237367D5
initial_creation_type: input
source_metadata:
  title: Śavari
  language: en
  description: 'Texts by and about the mahāsiddha Śavari/Śabari (ri khrod zhabs),
    the Hunter:'
  volume:
    30ae3f81d66d40efadbefa36283a661a:
      title: A Guru Yoga of Śavari
      parent: Guru Yoga
created_at: '2022-03-01T02:23:59.927179'
last_modified_at: '2022-03-01T02:23:59.927185'
